version: '2'

services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "8081:8080"
    environment:
      - OTEL_SERVICE_NAME=order-service
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - LOGGING_FILE_PATTERN=/logs/order-service/order-service.%d{yyyy-MM-dd}.%i.log
    volumes:
      - order_log_volume:/logs/order-service
    depends_on:
      - rabbitmq

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8082:8080"
    environment:
      - OTEL_SERVICE_NAME=inventory-service
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14250
      - LOGGING_FILE_PATTERN=/logs/inventory-service/inventory-service.%d{yyyy-MM-dd}.%i.log
    volumes:
      - inventory_log_volume:/logs/inventory-service
    depends_on:
      - rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"

  rabbitmq:
    image: rabbitmq:management
    restart: no
    ports:
      - "15672:15672"

  splunk:
    image: splunk/splunk:8.0
    hostname: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"

  splunkforwarder:
    image: splunk/universalforwarder:8.0
    hostname: splunkforwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes
      - SPLUNK_STANDALONE_URL=splunk:9997
      - SPLUNK_ADD=monitor /logs
      - SPLUNK_PASSWORD=password
    restart: always
    depends_on:
      splunk:
        condition: service_healthy
    volumes:
      - order_log_volume:/logs/order-service
      - inventory_log_volume:/logs/inventory-service

volumes:
  order_log_volume:
  inventory_log_volume:
